"""empty message

Revision ID: 95297dbf8cdc
Revises: 
Create Date: 2017-11-04 02:04:24.672154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95297dbf8cdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('poster_url', sa.String(length=256), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('session_start', sa.TIMESTAMP(), nullable=False),
    sa.Column('session_date', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie_genre',
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_genre')
    op.drop_table('movie')
    op.drop_table('genre')
    # ### end Alembic commands ###
