"""empty message

Revision ID: fce23ff4b6b4
Revises: 
Create Date: 2017-10-29 19:33:41.168036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce23ff4b6b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('poster_url', sa.String(length=256), nullable=True),
    sa.Column('price', sa.Float(precision=2), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('session_start', sa.TIMESTAMP(), nullable=True),
    sa.Column('session_date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie')
    # ### end Alembic commands ###
